swagger: '2.0'
info:
  version: 0.0.1
  title: multiLogin
host: localhost:10011
basePath: /
schemes:
  - http
  - https
tags:
  - name: login
consumes:
  - application/json
produces:
  - application/json
paths:
  /login:
    x-swagger-router-controller: user
    post:
      tags:
        - login
      description: Register a user in the app
      operationId: login
      parameters:
        - name: body
          in: body
          description: Login Body
          required: true
          schema:
            required:
              - email
              - password
            properties:
              email:
                format: email
                type: string
              password:
                type: string
      responses:
        '200':
          description: Successs
          schema:
            type: object
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /swagger:
    x-swagger-pipe: swagger_raw

definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
        description: a short comment
    required:
      - success
      - description
